name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Lint
        run: nr lint

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [14.x, 16.x]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Test
        run: nr test

      - name: Typecheck
        run: nr typecheck

  # build:
  #   strategy:
  #     matrix:
  #       node:
  #         - "16"
  #       platform:
  #         - ubuntu-latest
  #         - windows-latest
  #   name: "${{matrix.platform}} / Node.js ${{ matrix.node }}"
  #   runs-on: ${{matrix.platform}}
  #   steps:
  #     - name: Checkout Commit
  #       uses: actions/checkout@v3
  #     - name: Install pnpm
  #       uses: pnpm/action-setup@v2.2.4
  #       with:
  #         version: next-7
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: "pnpm"
  #     - name: Install npm@7
  #       run: npm add --global npm@7
  #     - name: pnpm install
  #       run: pnpm install
